# Derived from https://github.com/obi1kenobi/cargo-semver-checks/blob/main/.github/workflows/ci.yml

name: CI

on:
  pull_request:
  push:
  schedule:
    - cron: "0 7 * * *" # run once per day at 7:00 am

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  PACKAGE_NAME: entromatica

jobs:
  lint-and-test:
    name: Run tests, lint and rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          profile: minimal
          override: true

      - uses: Swatinem/rust-cache@v2

      - name: cargo clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --workspace --all-features --all-targets -- -D warnings --allow deprecated

      - name: Format and create commit if necessary
        uses: mbrobbel/rustfmt-check@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: test
        run: cargo test
