on:
  push:
    branches:
      - main
name: release-please
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: rust
          package-name: release-please-action
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true

      - name: Install rust
        uses: actions-rs/toolchain@v1
        if: ${{ steps.release.outputs.release_created }}
        with:
          toolchain: stable
          profile: minimal
          override: true

      - uses: Swatinem/rust-cache@v2
        if: ${{ steps.release.outputs.release_created }}

      - name: Publish
        if: ${{ steps.release.outputs.release_created }}
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
